name: Sync Leetcode

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: f964966828/leetcode-sync@master
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          verbose: true
          destination-folder: leetcode
          filter-duplicate-secs: 86400
          commit-header: "[LeetCode]"
